[project]
name = "MCP-RAG"
version = "0.1.0"
description = "A Simple MCP RAG with GroundX"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "groundx>=2.3.0",
    "ipykernel>=6.29.5",
    "mcp[cli]>=1.6.0",
    "openai>=1.75.0",
]
